[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "histokit"
version = "1.0.0"
authors = [
  { name="Julia Merta", email="julia.merta@polsl.pl" },
    { name="Michał Marczyk", email="michal.marczyk@polsl.pl" },
]
description = "HistoKit is a Python package for processing Whole Slide Images (WSIs). It provides a comprehensive toolkit for common WSI operations."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]


[project.urls]
Homepage = "https://zaedpolsl.github.io/HistoKit/"
Issues = "https://github.com/ZAEDPolSl/HistoKit/issues"