# cohort.yaml

slides:
  input_dir: C:/Repos/Data/Compass/svs/
  file_csv: null
  pattern: "*.svs"

output_dir: C:/Repos/Data/Compass/Results/
saver: hdf5

logging:
  enabled: true
  log_dir: ./outputs/logs
  processed_file: processed.csv
  errors_file: errors.csv

stages:
  tissue_detection:
    enabled: true
    algorithm: gamred
    config_path: ./gamred.yaml
    parallel_workers: 1
    overwrite: false

  artifact_detection:
    enabled: true
    algorithm: grandqc
    config_path: ./grandqc.yaml
    parallel_workers: 1
    overwrite: false
    tissue_source:
      algorithm: gamred
