# cohort.yaml

slides:
  input_dir: C:/Repos/Data/Compass/svs/
  file_csv: null
  pattern: "*.svs"
  
output_dir: C:/Repos/Data/Compass/results/
saver: hdf5

logging:
  enabled: true
  log_dir: ./outputs/logs
  processed_file: processed.csv
  errors_file: errors.csv

stages:
  tissue_detection:
    enabled: true
    mag_l0: 10.0
    algorithm: hethr
    config_path: ./hethr.yaml
    parallel_workers: 1
    overwrite: false