# cohort.yaml

slides:
  input_dir: C:/Repos/Data/GrandQC/png/
  file_csv: null
  pattern: "*.png"
  
output_dir: C:/Repos/Data/GrandQC/res/
saver: hdf5

logging:
  enabled: true
  log_dir: ./outputs/logs
  processed_file: processed.csv
  errors_file: errors.csv

stages:
  tissue_detection:
    enabled: false
    mag_l0: 10.0
    algorithm: gamred
    config_path: ./gamred.yaml
    parallel_workers: 1
    overwrite: false

  artifact_detection:
    enabled: true
    algorithm: grandqc
    mag_l0: 10.0
    config_path: ./grandqc.yaml
    parallel_workers: 1
    overwrite: false
    tissue_source:
      dir: None