# grandqc.yaml

# output
saver: hdf5
out_dir: ./outputs/
save_mag: 1.0

# model
model_path: C:/Repos/HistoKit/models/GrandQC_MPP1.pth

# inference
device: cuda:0
batch_size: 16
num_workers: 2

# magnification
grandqc_mpp: 1.0
det_mag: 10.0
vis_mag: 2.5

# patches
patch_size_model: 512 
patch_size: 512
overlap: 0.9
grid_offset: 0.5
pad_value: 255

# blending
blending_mode: constant
blending_sigma: 1.25

# network
encoder: timm-efficientnet-b0
encoder_weights: imagenet
classes: 8

# outputs
save_confidence_maps: true
save_raw_mask: true

# visualizations
collectors:
  - name: ArtifactOverlayCollector