# hethr.yaml

algorithm_name: HeThr

# output
saver: hdf5
out_dir: ./outputs/
save_mag: 10.0

# magnification settings
vis_mag: 1.0
tissdet_mag: 10.0
blur_kernel_width: 0
nbins: 256

# outputs / visualizations
collectors:
  - name: ThumbnailCollector
  - name: SegmentationOverlayCollector
  - name: MaskCollector

postprocess_steps: []